---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: pinniped-cli version
    register: pinniped_test_output
  - name: pinniped-cli version
    debug:
      msg: '{{ pinniped_test_output.stdout }}'
