---
- name: Testing andrewrothstein.pinniped
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'pinniped-cli version'
      ansible.builtin.command: pinniped-cli version
      changed_when: false
      register: pinniped_test_output
    - name: Output of 'pinniped-cli version'
      ansible.builtin.debug:
        msg: '{{ pinniped_test_output.stdout }}'
