---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Downloading {{ pinniped_url }} to {{ pinniped_exe }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ pinniped_url }}'
    dest: '{{ pinniped_exe }}'
    checksum: '{{ pinniped_checksum }}'
    mode: '755'
- name: Linking {{ pinniped_link }} to {{ pinniped_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ pinniped_exe }}'
    dest: '{{ pinniped_link }}'
    state: link
